
public with sharing class SuperheroMissionService {

//    private static final String EMAIL_SUBJECT = 'New Superhero Mission Created';
//    private static final String EMAIL_BODY = 'A new superhero mission has been created. Check it out!';
//
//    public static void notifyGuildMembers(List<Id> guildIds) {
//        List<String> guildEmails = new List<String>();
//
//        for (Hero__c hero : [SELECT Name, Contact__r.Email  FROM Hero__c WHERE Guild__c IN :guildIds]) {
//            guildEmails.add(hero.Contact__r.Email);
//        }
//
//        if (!guildEmails.isEmpty()) {
//            EmailService.sendEmail(guildEmails, EMAIL_SUBJECT, EMAIL_BODY);
//        }
//    }
}